Solar:
  batch_size: 2048
  config_path: logs/sweeps/s5/Solar/2026-01-29/best_models/rank_01_sweep_s5_20260129_121708_hyyz13rk_config.yaml
  dataset_name: Solar
  delay: 0
  directory: logs/sweeps/s5/Solar/2026-01-29/best_models
  epochs: 9
  file_name: rank_01_sweep_s5_20260129_121708_hyyz13rk_config.yaml
  grad_clip_val: 5.0
  horizon: 12
  learning_rate: 0.0004878493167912685
  loss_fn: mae
  model_dropout: 0
  model_hidden_size: 70
  model_n_layers: 4
  model_name: s5
  patience: 10
  stride: 1
  timestamp: '20260129_121708'
  val_loss: 0.129474
  weight_decay: 0.0005
  window_size: 64
